# Generated by Django 4.2.7 on 2023-11-18 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomePlusStore', '0002_articulo_categoriaarticulo_preciohistorico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('sueldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Documentopersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id_colaborador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('documento_identidad', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('direccion', models.TextField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('numero_telefono', models.CharField(max_length=20)),
                ('fecha_contratacion', models.DateField(auto_now_add=True)),
                ('perfil', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('contraseña', models.CharField(default='mi_valor_predeterminado', max_length=255)),
                ('Documentopersonal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HomePlusStore.documentopersonal')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePlusStore.cargo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePlusStore.departamento')),
                ('rol', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HomePlusStore.rol')),
            ],
        ),
    ]
